#!/usr/bin/python
# Copyright 2014 Google.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generates a list of all encodings for a given filename / bitrate.
#
import argparse
import sys

import encoder
import pick_codec
def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('rate')
  parser.add_argument('videofile')
  parser.add_argument("--codec")
  args = parser.parse_args()

  videofile = encoder.Videofile(args.videofile)

  bitrate = int(args.rate)

  print "Codec is", args.codec

  videofile = encoder.Videofile(args.videofile)

  codec = pick_codec.PickCodec(args.codec)

  print codec.DisplayHeading()
  for encoding in codec.AllScoredEncodings(bitrate, videofile).encodings:
    print encoding.encoder.Hashname(),
    print encoding.Score(), encoding.encoder.DisplayValues(),
    print encoding.result

  return 0

if __name__ == '__main__':
  sys.exit(main())

