#!/bin/bash
#
# Runs all unit tests for the tweaker
#
set -e

WORKDIR=$(dirname $0)

$WORKDIR/encoder_unittest.py
$WORKDIR/vp8_unittest.py
$WORKDIR/vp8_cq_unittest.py
$WORKDIR/vp8_mpeg_unittest.py
$WORKDIR/vp8_mpeg_1d_unittest.py
$WORKDIR/x264_unittest.py
$WORKDIR/h261_unittest.py
$WORKDIR/mjpeg_unittest.py
$WORKDIR/visual_metrics_unittest.py
