#!/bin/bash
#
# Runs all unit tests
#
set -e

WORKDIR=$(dirname $0)

$WORKDIR/encoder_unittest.py
$WORKDIR/score_tools_unittest.py
$WORKDIR/vp8_unittest.py
$WORKDIR/vp8_mpeg_unittest.py
$WORKDIR/vp8_mpeg_1d_unittest.py
$WORKDIR/x264_unittest.py
$WORKDIR/h261_unittest.py
$WORKDIR/mjpeg_unittest.py
$WORKDIR/visual_metrics_unittest.py
$WORKDIR/pick_codec_unittest.py
$WORKDIR/file_codec_unittest.py
$WORKDIR/vp9_unittest.py

pylint $(ls lib/*.py | grep -v 'gviz_api.py')
