#!/bin/sh
# Copyright 2015 Google.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Get some videos to run comparisons on.
#
set -e

cd $WORKDIR/video

# The Derf collection is easily available via rsync.
rsync -avz --max-size=100M rsync://media.xiph.org/y4m derf

# The WEBM collection is accessible via a script that expects the
# dirname "video", but not via rsync.
if [ ! -d webm ]; then
   mkdir webm
   cd webm
   ../fetch_webm_videos.sh
fi

# Some test files
if [ ! -d testclips ]; then mkdir testclips; fi

framesize=$(expr 1024 \* 768 \* 3 / 2)
# One frame, all black.
dd if=/dev/zero of=testclips/one_black_frame_1024_768_30.yuv \
    bs=$framesize count=1
